name: React Native Firebase CI (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies (Fix Conflicts)
        run: npm install --legacy-peer-deps

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Login to Firebase (Skip for CI)
        run: firebase login:ci --no-localhost
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Lint Code
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build
